version: '3.8'

services:
  mysql-task-db:
    image: mysql:8.0
    container_name: mysql-task-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_service_db
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpassword
    ports:
      - "3308:3306"
    volumes:
      - task_mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  task_mysql_data: